spring:
  security:
    oauth2:
      client:
        registration:
          gitlab:
            provider: gitlab
            redirect-uri: http://localhost:8080/login/oauth2/code/gitlab
            authorization-grant-type: authorization_code
            client-id: "1a8267c12e72245e933f2634391aa837aa3e45d2e768cc17b6a32da943c575c8"
            client-secret: "gloas-24bd0dbad1c3f62008e76a2e0026f49ce3c5552281c41d81021bd98f8a2e830a"