spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        provider:
          gitlab:
            authorization-uri: https://gitlab.lrz.de/oauth/authorize
            token-uri: https://gitlab.lrz.de/oauth/token
            user-info-uri: https://gitlab.lrz.de/api/v4/user
            user-name-attribute: username

  cloud:
    gateway:
      mvc:
        routes:
          - id: darkmode-api
            uri: http://darkmode-api:8080
            predicates:
              - Path=/darkmode/**
            filters:
              - StripPrefix=1
          - id: compiler-api
            uri: http://compiler-api:8080
            predicates:
              - Path=/compiler/**
            filters:
              - StripPrefix=1
          - id: frontend
            uri: http://frontend:8080
            predicates:
              - Path=/ui/**
            filters:
              - StripPrefix=1
              - TokenRelay=
              - RemoveRequestHeader=Cookie
              - RemoveRequestHeader=Set-Cookie
          - id: project
            uri: http://project-api:8080
            predicates:
              - Path=/backend/**
            filters:
              - StripPrefix=1
              - TokenRelay=
              - RemoveRequestHeader=Cookie
              - RemoveRequestHeader=Set-Cookie

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://service-discovery:8761/eureka}